name: Build Palisades

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore Palisades.sln

    - name: Build with MSBuild
      run: msbuild Palisades.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Custom-Palisades-App
        path: Palisades.Application/bin/Release/
